import { NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
    },
    {
        key: 'schedule',
        path: '/schedule',
        title: 'Schedule',
        translateKey: 'nav.schedule',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    {
        key: 'shifts',
        path: '/shifts',
        title: 'Shifts',
        translateKey: 'nav.shifts',
        icon: 'clock',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER', 'STAFF'],
        subMenu: [],
    },
    {
        key: 'swaps',
        path: '/swaps',
        title: 'Swaps',
        translateKey: 'nav.swaps',
        icon: 'switchHorizontal',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER', 'STAFF'],
        subMenu: [],
    },
    {
        key: 'availability',
        path: '/availability',
        title: 'Availability',
        translateKey: 'nav.availability',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'STAFF'],
        subMenu: [],
    },
    {
        key: 'staff',
        path: '/staff',
        title: 'Staff',
        translateKey: 'nav.staff',
        icon: 'userGroup',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    {
        key: 'fairness',
        path: '/fairness',
        title: 'Fairness Dashboard',
        translateKey: 'nav.fairness',
        icon: 'chartBar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '/reports',
        title: 'Reports',
        translateKey: 'nav.reports',
        icon: 'documentText',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
]

export default navigationConfig
