import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'



import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    // ADMIN & MANAGER
    {
        key: 'schedule',
        path: '/schedule',
        title: 'Schedule',
        translateKey: 'nav.schedule',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    {
        key: 'shifts',
        path: '/shifts',
        title: 'Shifts',
        translateKey: 'nav.shifts',
        icon: 'clock',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    {
        key: 'swap-requests',
        path: '/swaps',
        title: 'Swap Requests',
        translateKey: 'nav.swapRequests',
        icon: 'switchHorizontal',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    {
        key: 'staff',
        path: '/staff',
        title: 'Staff',
        translateKey: 'nav.staff',
        icon: 'userGroup',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MANAGER'],
        subMenu: [],
    },
    // STAFF
    {
        key: 'my-shifts',
        path: '/shifts',
        title: 'My Shifts',
        translateKey: 'nav.myShifts',
        icon: 'clock',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'my-availability',
        path: '/availability',
        title: 'My Availability',
        translateKey: 'nav.myAvailability',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'my-swaps',
        path: '/swaps',
        title: 'Swap Requests',
        translateKey: 'nav.mySwaps',
        icon: 'switchHorizontal',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['STAFF'],
        subMenu: [],
    },
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'singleMenuItem',
        path: '',
        title: 'Single menu item',
        translateKey: 'nav.singleMenuItem',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'collapseMenu',
        path: '',
        title: 'Collapse Menu',
        translateKey: 'nav.collapseMenu.collapseMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'collapseMenu.item1',
                path: '',
                title: 'Collapse menu item 1',
                translateKey: 'nav.collapseMenu.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.item2',
                path: '',
                title: 'Collapse menu item 2',
                translateKey: 'nav.collapseMenu.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'groupMenu',
        path: '',
        title: 'Group Menu',
        translateKey: 'nav.groupMenu.groupMenu',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'groupMenu.single',
                path: '',
                title: 'Group single menu item',
                translateKey: 'nav.groupMenu.single',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.collapse',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.collapse.collapse',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.collapse.item1',
                        path: '',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.collapse.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collapse.item2',
                        path: '',
                        title: 'Menu item 2',
                        translateKey: 'nav.groupMenu.collapse.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default navigationConfig
